# Generated by Django 4.1.5 on 2023-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=50, verbose_name='isbn')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('year', models.CharField(max_length=50, verbose_name='year')),
            ],
        ),
    ]
