# Generated by Django 4.1.5 on 2023-08-29 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PavementCrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='lat')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='long')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('inspection_date', models.DateTimeField()),
                ('repair_date', models.DateTimeField()),
                ('repair_type', models.IntegerField()),
                ('d00', models.IntegerField()),
                ('d10', models.IntegerField()),
                ('d20', models.IntegerField()),
                ('d40', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
