# Generated by Django 4.1.5 on 2023-08-29 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pavement_crack', '0002_pavementcrack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavementcrack',
            name='d00',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='d10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='d20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='d40',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='inspection_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='repair_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='repair_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
