# Generated by Django 4.1.5 on 2023-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavement_crack', '0003_alter_pavementcrack_d00_alter_pavementcrack_d10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavementcrack',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pavementcrack',
            name='long',
            field=models.FloatField(),
        ),
    ]
